INSERT INTO TEAM(NAME,TEAM_LEAD) VALUES('Team A','Matt Hardy');
INSERT INTO TEAM(NAME,TEAM_LEAD) VALUES('Team B','Chester Bennington');
INSERT INTO TEAM(NAME,TEAM_LEAD) VALUES('Team C','Mike Shinoda');
INSERT INTO TEAM(NAME,TEAM_LEAD) VALUES('Team D','Rob Delson');

INSERT INTO PROJECT(NAME,PROJECT_MANAGER_ID) VALUES('Rover','1122');
INSERT INTO PROJECT(NAME,PROJECT_MANAGER_ID) VALUES('Mars Exploration','1132');
INSERT INTO PROJECT(NAME,PROJECT_MANAGER_ID) VALUES('Meteor Detection','1142');
INSERT INTO PROJECT(NAME,PROJECT_MANAGER_ID) VALUES('Satellite Rio','1152');